services:
  mysql:
    image: mysql:8.4
    container_name: praktikum-mysql
    environment:
      MYSQL_DATABASE: praktikum_db
      MYSQL_USER: praktikum
      MYSQL_PASSWORD: praktikum
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - praktikum_mysql_data:/var/lib/mysql

volumes:
  praktikum_mysql_data: